# Module manifest for module 'PSBandcamp'
# Generated by: Lage Berger Jensen
# Generated on: 07.02.20

@{
    RootModule        = 'PSBandcamp.psm1'
    ModuleVersion     = '1.0.0'
    GUID              = '0fbdf65f-3373-46dd-b571-7705b52b7aed'
    Author            = 'Lage Berger Jensen'
    CompanyName       = ''
    Copyright         = '(c) 2020 Lage Berger Jensen. All rights reserved.'
    Description       = ''
    FunctionsToExport = @(
        'New-Playlist',
        'Start-Playlist'
    )
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
    # CompatiblePSEditions = @()
    # PowerShellVersion = ''
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # CLRVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()
    PrivateData       = @{
        PSData = @{
            # Tags = @()
            LicenseUri = 'https://github.com/lagebj/PSBandcamp/blob/master/LICENSE'
            ProjectUri = 'https://github.com/lagebj/PSBandcamp'
            # IconUri = ''
            ReleaseNotes = 'https://github.com/lagebj/PSBandcamp/blob/master/ReleaseNotes.md'
        }
    }
    # HelpInfoURI = ''
    DefaultCommandPrefix = 'Bandcamp'
}
